name       : haskell-GLURaw
version    : 2.0.0.2
release    : 1
source     :
    - http://hackage.haskell.org/package/GLURaw-2.0.0.2/GLURaw-2.0.0.2.tar.gz : 884b3dbefbaabdc66cf8e240d33adb0d491bcf9119e53a7d42b8cf0972df15de
license    : BSD-3-Clause
component  : programming
summary    : GLURaw is a raw Haskell binding for the GLU 1.3 OpenGL utility library.
description: |
    GLURaw is a raw Haskell binding for the GLU 1.3 OpenGL utility library.
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-OpenGLRaw
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup %JOBS% build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 GLURaw-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/GLURaw-$version.conf
