name       : haskell-GLURaw
version    : 2.0.0.4
release    : 4
source     :
    - https://hackage.haskell.org/package/GLURaw-2.0.0.4/GLURaw-2.0.0.4.tar.gz : b863fd5cb26b1a37afb66ef8a81c0335bc073d33b0a67ec5190dfc62cb885dc4
license    : BSD-3-Clause
component  : programming.haskell
summary    : GLURaw is a raw Haskell binding for the GLU 1.3 OpenGL utility library.
description: |
    GLURaw is a raw Haskell binding for the GLU 1.3 OpenGL utility library.
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-cabal-install
    - haskell-OpenGLRaw
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
